version: '3.11'

services:
  deposit-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.main:app --host localhost --port 8000
    volumes:
      - .:/app
