version: "3.11"
services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_menti_dep
    ports:
      - "5445:5445"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5445/db_menti_dep
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
