version: '3.11'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: poetry run pytest --cov=src --cov-report=term-missing

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: poetry run uvicorn src.app.main:app --host 0.0.0.0 --port 8000


